lana/b2c-mapp-ui

- package-lock.json
- package.json
- src/forms/Field/index.jsx
Fixes to security issue, and a quick hotfix.
> Hotfix, update packages to fix security issues.

- package-lock.json
- package.json
- src/forms/Toggle/index.jsx
- src/lists/ActionItem/index.jsx
- src/lists/ContentItem/index.jsx
- src/lists/ListCopyable/index.jsx
- src/lists/ListItem/index.jsx
- src/navigation/Stepper/index.jsx
- src/navigation/TopBar/index.jsx
- src/overlays/BottomDialog/index.jsx
- src/overlays/Dialog/index.jsx
- src/typography/Heading/index.jsx
- src/typography/Text/index.jsx
Provide data-testid attribute for inner elements in all the components to improve the way we test them. 
Specially made to test with `preact-testing-library` however it will be also valid to test with enzyme.
*Note: More `data-testid` could be added if you think its a good idea in some case that I didn't cover yet.
> Provide data-test-id for everyone

- .github/workflows/nodejs.yml
- src/components/Screen/styles.css
- src/components/ScrollWrapper/ScrollWrapper.jsx
- src/components/ScrollWrapper/styles.css
Apply scroll fix to new ui version -> ![Link to PR](https://github.com/lana/b2c-mapp-ui/pull/23)
> Fix scroll issues

- src/components/ScrollWrapper/styles.css
Short lists scroll component fix to keep the height.
> Flex grow for short lists

- package.json
- src/components/ComingSoon/ComingSoon.stories.js
- src/components/ComingSoon/ComingSoon.vue
This PR will add a small fix: Add action to Aceptar button in the Storybook. Also will update the Header title size to xl.
- npm run lint: PASS
- npm run test: PASS
- npm run storybook: PASS
> Small fix: Add action to Aceptar button 

- package.json
* Bumped patch version (required for re-releasing the latest version)
N/A
> Bumped patch version

- package.json
- src/components/StorybookMobileDeviceSimulator/StorybookMobileDeviceSimulator.js
This PR will resolve #40 by adding new sizes to StorybookMobileDeviceSimulator
**npm run test: PASS
**npm run lint: PASS
> Add new sizes to StorybookMobileDeviceSimulator

- package-lock.json
- package.json
Updates version of assets to 4.1.1
> Version updates

- package-lock.json
- package.json
- src/components/ActionItem/ActionItem.js
- src/components/ActionItem/ActionItem.stories.js
- src/components/ActionItem/ActionItem.vue
- src/components/Checkbox/Checkbox.js
- src/components/Checkbox/Checkbox.scss
- src/components/Checkbox/Checkbox.stories.js
- src/components/Checkbox/Checkbox.test.js
- src/components/Checkbox/Checkbox.vue
- src/components/Infobox/Infobox.js
- src/components/Infobox/Infobox.scss
- src/components/Infobox/Infobox.stories.js
- src/components/Infobox/Infobox.vue
- src/components/PhoneNumberField/PhoneNumberField.test.js
- src/components/RadioList/RadioList.test.js
- src/components/SelectBox/SelectBox.test.js
- src/components/Stepper/Stepper.test.js
- src/components/TextField/TextField.test.js
- src/components/ToggleSwitch/ToggleSwitch.test.js
- src/components/TopBar/TopBar.test.js
- src/components/WrappedButton/WrappedButton.test.js
* Updated NPM dependencies to their latest versions.
* Bumped the MINOR version in package.json
* Removed orphan `// TODO:` comments
* Updated the `ActionItem` component: added new `description` and `status` props.
* Added a new `Checkbox` component with unit tests and Storybook stories
* Added a new `Infobox` component with Storybook stories.
> Update and add new components

- package-lock.json
- package.json
- src/library.js
* Added missing `Infobox` export to `library.js`.
* Updated NPM dependencies to their latest versions.
* Bumped the MINOR version in `package.json`
> Added missing Infobox export

- package-lock.json
- package.json
- src/components/RadioList/RadioList.js
Bumped the MINOR version in package.json. Updated NPM dependencies. Updated RadioList's value prop to accept either Number or String
> Fix RadioList value prop type

- CHANGELOG.md
- package-lock.json
- package.json
New assets version with FAQ icons:
> New assets version

- package-lock.json
- package.json
- src/components/FormField/FormField.js
- src/components/FormField/FormField.stories.js
- src/components/FormField/FormField.vue
- src/components/TextField/TextField.js
- src/components/TextField/TextField.stories.js
- src/components/TextField/TextField.vue
* Updated `FormField` and `TextField` components to emit `keyup` and `keypress` events.
* Updated NPM Dependencies.
*  `npm run test`: **PASS**
*  `npm run lint`: **PASS**
*  Local testing with Storybook: **PASS**
> Updated FormField and TextField to emit keyup and keypress events.

- package-lock.json
- package.json
- src/components/Checkbox/Checkbox.js
- src/components/Checkbox/Checkbox.vue
- src/components/ComingSoon/ComingSoon.js
- src/components/ComingSoon/ComingSoon.vue
- src/components/ListItem/ListItem.js
- src/components/ListItem/ListItem.scss
- src/components/ListItem/ListItem.stories.js
- src/components/ListItem/ListItem.vue
- src/components/SlideButton/SlideButton.js
- src/components/SlideButton/SlideButton.scss
- src/components/SlideButton/SlideButton.stories.js
- src/components/SlideButton/SlideButton.vue
- src/library.js
- src/styles/_colors.scss
- Updating the ListItem component to have value in right.
- Creating Slider component.
I have tested both of the features in storybooks.
> Adding basic slide button.

- package-lock.json
- package.json
* Updated latest npm dependencies (including a severe security fix)
> Updated latest npm dependencies (including a severe security fix)

- package-lock.json
- package.json
- src/components/SelectBox/SelectBox.stories.js
* Updated NPM dependencies.
* Fixed Storybook error for a `SelectBox` story
> Updated NPM dependencies. Fixed Storybook error for SelectBox story

- package-lock.json
- package.json
* Updated to the latest NPM dependencies
> Updated to the latest NPM dependencies

- config/storybook/main.js
- package-lock.json
- package.json
* Updated NPM Dependencies.
* Bumped the `PATCH` version in `package.json`.
* Updated the display order of Storybook add-on tabs.
> Updated NPM Dependencies

- package-lock.json
- package.json
- Update assets version to support UpdateApp icon + improvements to fix color issues on FAQ icons.
- Working on storybook ❤️
> Assets update

- package-lock.json
- package.json
- src/components/Button/Button.test.js
- src/components/Button/Button.vue
* Fixed the `:href` binding for the `Button` component and updated its unit tests to check for it.
* Updated NPM dependencies to the latest versions.
* Bumped the `PATCH` version in `package.json`.
> Fix button href

- package-lock.json
- package.json
- src/components/ContentItem/ContentItem.js
- src/components/ContentItem/ContentItem.vue
Add chevron instead of forward icon to ContentItem.
Apply last assets version with `.vue` exported icons for FAQs to fix color issues.
Describe the testing steps you've taken
> Style fix for ContentItem and last assets version

- package-lock.json
- package.json
- src/library.js
* Added missing `CurrencyField` export to `library.js`.
* Updated NPM dependencies.
> Fix CurrencyField export

- package-lock.json
- package.json
- src/components/DateField/DateField.js
- src/components/DateField/DateField.stories.js
- src/components/DateField/DateField.test.js
- src/lib/dateHelper.js
The goal is to handle correctly some dates that are flagged as valid when they are not, like `29/02/2019`
Input a date that seems to be valid, and expect an Invalid value flag
> DateField invalid date checker

- package-lock.json
- package.json
- src/library.js
* Added `CodeInputField` to `library.js` (I had forgotten to add it in my previous PR 😞 ) 
> Added CodeInputField to library.js

- package-lock.json
- package.json
- src/components/CurrencyField/CurrencyField.scss
- src/components/FormField/FormField.scss
- src/components/PhoneNumberField/PhoneNumberField.stories.js
- src/components/SelectBox/SelectBox.scss
* Fixed the height of FormField (and similar) components.  
* Updated NPM Dependencies
> Update field heights

- package-lock.json
- package.json
- src/components/CurrencyField/CurrencyField.scss
- src/components/FormField/FormField.scss
* Fixed the clear button's vertical-alignment for `FormField` and `CurrencyField` components.
> Fix form field clear button alignment

- .eslintrc.js
- package-lock.json
- package.json
- src/components/CurrencyField/CurrencyField.js
- src/components/CurrencyField/CurrencyField.scss
- src/components/CurrencyField/CurrencyField.vue
- src/components/DateField/DateField.scss
- src/components/FormField/FormField.js
- src/components/FormField/FormField.scss
- src/components/FormField/FormField.vue
- src/components/PhoneNumberField/PhoneNumberField.scss
- src/components/SelectBox/SelectBox.scss
* Fixed more forms style/UX issues (reported by design, see issue here: https://github.com/lana/b2c-mapp-ui/issues/97 for more details)
* Updated NPM dependencies
* Bumped the `PATCH` version in `package.json
> #97 More Forms UX improvements

- package-lock.json
- package.json
- src/components/ContentItem/ContentItem.js
- src/components/ContentItem/ContentItem.scss
- src/components/ContentItem/ContentItem.stories.js
- src/components/ContentItem/ContentItem.test.js
- src/components/ContentItem/ContentItem.vue
Provide a success state to content item.
- No "forward" icon is shown -> Success icon will be shown instead.
- No event should be emitted onClick, it will be just informative element, no user-interaction.
Minor style improvements
Before:
After:
- tested in Storybook
- unit tests
- [] **PATCH** backwards-compatible bug fixes.
> Success variant of ContentItem

- package-lock.json
- package.json
- src/components/ContentItem/ContentItem.scss
Bolder font-weight should be applied manually instead... it breaks most of the designs applying it in the original component.
- Storybook
- Unit tests not needed.
Before:
After:
> Revert font-weight to previous value

- package-lock.json
- package.json
> Icon updates

- package-lock.json
- package.json
- src/components/ForwardButton/ForwardButton.scss
* Added a high `z-index` CSS property to the Forward-button's wrapper in order to prevent issues from users being unable to click it when it's hovering over some form elements.
* Updated npm dependencies.
> Fix ForwardButton's z-index

- package-lock.json
- package.json
- src/components/ContentItem/ContentItem.js
- src/components/ContentItem/ContentItem.scss
- src/components/ContentItem/ContentItem.vue
Add active style for ContentItem component (requested by design team)
- npm run lint: pass
- npm run test: pass
- npm run storybook: pass
> Add active style for ContentItem component

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/ListItem/ListItem.js
- src/components/ListItem/ListItem.stories.js
- src/components/ListItem/ListItem.test.js
- src/components/ListItem/ListItem.vue
I need a new variant for the ListItem component to provide a Checkbox instead of a toggle. This new component will be used soon in this new screens
Just added a new prop -> `hasCheckbox` and added missing unit-tests to ensure the behavior is the expected.
Also added a Storybook knob to handle it.
> ListItem variant to provide checkbox instead of toggle

- package-lock.json
- package.json
> Update icons from latest b2c-mapp-ui-assets

- package-lock.json
- package.json
- src/components/ContentItem/ContentItem.stories.js
Some stories didn't behave as expected
Tested on storybook
> Fix ContentItem stories

- package-lock.json
- package.json
- src/components/FigureCard/FigureCard.js
- src/components/FigureCard/FigureCard.stories.js
- src/components/FigureCard/FigureCard.vue
Update figure card to have title displayed up
- npm run test: *pass*
- npm run lint: *pass*
> Update figure card to have title displayed up

- package-lock.json
- package.json
- src/components/FigureCard/FigureCard.scss
- src/components/FigureCard/FigureCard.vue
Fix style for title above FigureCard
Tested locally with storybook
- npm run test: passed
- npm run lint: passed
> Fix style for title above FigureCard

- package-lock.json
- package.json
- src/library.js
Added Checkbox to library so it can be exported
> Fix Checkbox import

- config/storybook/main.js
- package-lock.json
- package.json
- src/components/ContentRadioList/ContentRadioList.js
- src/components/ContentRadioList/ContentRadioList.stories.js
- src/components/ContentRadioList/ContentRadioList.test.js
- src/components/ContentRadioList/ContentRadioList.vue
- src/components/Icons/Icons.stories.js
- src/lib/renderString.js
- src/library.js
Add import to library.js 
**Extra**: Installed `addon-controls` and added a prototype for controls on ContentRadioList
> Fix ContentRadioList import

- package-lock.json
- package.json
- src/components/ActionItem/ActionItem.stories.js
- src/components/ContentItem/ContentItem.js
- src/components/ContentRadioList/ContentRadioList.stories.js
> ActionItem stories

- package-lock.json
- package.json
- src/components/BoxContentItem/BoxContentItem.js
- src/components/BoxContentItem/BoxContentItem.scss
- src/components/BoxContentItem/BoxContentItem.stories.js
- src/components/BoxContentItem/BoxContentItem.vue
Addition of BoxContentItem component
> Box content item

- package-lock.json
- package.json
- src/components/BoxContentItem/BoxContentItem.stories.js
- src/library.js
Export BoxContentItem in library, changed *div* for *ul* in this component's stories
> Export BoxContentItem in library

- package-lock.json
- package.json
- src/components/ConfirmationToastDialog/ConfirmationToastDialog.stories.js
- src/components/ConfirmationToastDialog/ConfirmationToastDialog.test.js
- src/components/ConfirmationToastDialog/ConfirmationToastDialog.vue
- src/lib/renderString.js
Add a slot for actions, to override current behavior with a custom one
> ConfirmationToastDialog custom actions slot

- config/storybook/main.js
- jest.config.js
- mage.go
- package-lock.json
- package.json
- src/components/AmountInput/AmountInput.js
- src/components/AmountInput/AmountInput.scss
- src/components/AmountInput/AmountInput.stories.js
- src/components/AmountInput/AmountInput.test.js
- src/components/AmountInput/AmountInput.vue
- src/library.js
Add a component that allows enter an amount and behaves as a normal element
> AmountInput

- package-lock.json
- package.json
- src/components/AmountInput/AmountInput.scss
- src/styles/_typography.scss
AmountInput has a wrong weight and typography
> Fix AmountInput typography

- package-lock.json
- package.json
- src/components/Carousel/Carousel.js
- src/components/Carousel/Carousel.stories.js
- src/components/CarouselItem/CarouselItem.js
- src/components/CarouselItem/CarouselItem.scss
- src/components/CarouselItem/CarouselItem.vue
Allow CarouselItem to have an inline width, improving Carousel value detection
> CarouselItem self width

- package-lock.json
- package.json
- src/components/Carousel/Carousel.js
- src/components/Carousel/Carousel.stories.js
Mounted v-model value was not being used and the default slide was always 0, fixed that.
Fixed scroll behavior when click and drag the carousel
> Fix Carousel mounted behavior

- package-lock.json
- package.json
- src/library.js
Forgot to export component SpecCard 🤦
> I like to create UI versions

- package-lock.json
- package.json
- src/components/ActionItem/ActionItem.scss
- src/components/BankAccountNumberInputField/BankAccountNumberInputField.js
- src/components/Checkbox/Checkbox.scss
- src/components/ContentItem/ContentItem.scss
- src/components/CopyableListItem/CopyableListItem.scss
- src/components/ListItem/ListItem.scss
- src/lib/regexHelper.js
- Stories were not working now are fixed
- Fixed copy-paste issues with bankaccount: https://sentry.io/organizations/lana-fintech-internacional/issues/2443133041/?project=5208202&referrer=slack
- 
Unit tested & tested in Storybook
Error when copying-pasting a CLABE with a \n at the end:
> UI library fix

- package-lock.json
- package.json
- src/components/LinearProgress/LinearProgress.js
- src/components/LinearProgress/LinearProgress.scss
- src/components/LinearProgress/LinearProgress.stories.js
- src/components/LinearProgress/LinearProgress.test.js
- src/components/LinearProgress/LinearProgress.vue
- src/components/Progress/Progress.js
- src/components/Progress/Progress.scss
Create new component for showing a progress, but in a linear way
Single element:
With SpecCard example:
> LinearProgress

- package-lock.json
- package.json
- src/components/LinearProgress/LinearProgress.js
- src/components/LinearProgress/LinearProgress.stories.js
- src/components/LinearProgress/LinearProgress.vue
- src/components/Progress/Progress.js
- src/components/Progress/Progress.scss
- src/components/Progress/Progress.stories.js
- src/components/Progress/Progress.test.js
- src/components/Progress/Progress.vue
Add the possibility to animate the progression with the `Animation` API
> LinearProgress animation

- package-lock.json
- package.json
- src/library.js
Fix Timeline missing export on library
> Fix Timeline component export

- package-lock.json
- package.json
- src/library.js
Include LinearProgress to the library
> Fix LinearProgress export

- package-lock.json
- package.json
- src/components/ToggleSwitch/ToggleSwitch.vue
Add the possibility to have the 2 options deselected for `null` value on buttons mode
> Fix ToggleSwitch focused behavior value check

- package-lock.json
- package.json
- src/components/BankAccountNumberInputField/BankAccountNumberInputField.stories.js
- src/components/PhoneNumberField/PhoneNumberField.js
- src/components/PhoneNumberField/PhoneNumberField.stories.js
Allow user to see the formatted number on the PhoneNumberField, it was showing the bound value
> Fix PhoneNumberField display format

- package-lock.json
- package.json
- src/components/SignaturePad/SignaturePad.js
- src/components/SignaturePad/SignaturePad.scss
- src/components/SignaturePad/SignaturePad.stories.js
- src/components/SignaturePad/SignaturePad.vue
Custom signature pad for user to draw their signature
> SignaturePad

- package-lock.json
- package.json
- src/components/SignaturePad/SignaturePad.js
- src/library.js
Add SignaturePad to library.js file
> Fix SignaturePad export

- package-lock.json
- package.json
- src/components/BoxContentItem/BoxContentItem.ts
- src/components/ContentItem/ContentItem.stories.ts
- src/components/ContentItem/ContentItem.ts
- src/components/CopyToClipboardButton/CopyToClipboardButton.ts
- src/components/CurrencyField/CurrencyField.test.ts
- src/components/CurrencyInput/CurrencyInput.vue
- src/components/ListItem/ListItem.ts
- src/components/SignaturePad/SignaturePad.ts
- src/lib/sleepHelper.ts
Some components were comparing wrong comments for default slot detection, importing the right one solved the issue
> Fix default slot detection

- package-lock.json
- package.json
- src/components/ContentRadioList/ContentRadioList.stories.ts
- src/components/ContentRadioList/ContentRadioList.ts
- src/components/ContentRadioList/ContentRadioList.vue
- src/lib/renderString.ts
Add an open possibility to implement a media icon to ContentRadioList through a new slot
> ContentRadioList media slot

- analyze.config.ts
- jest.config.js
- package-lock.json
- package.json
- src/components/SliderInput/SliderInput.scss
- src/components/SliderInput/SliderInput.stories.ts
- src/components/SliderInput/SliderInput.test.ts
- src/components/SliderInput/SliderInput.ts
- src/components/SliderInput/SliderInput.vue
- src/library.ts
- vite.config.ts
Add a new component to input a value with a slider.
> SliderInput component
