CHANGELOG.md, package-lock.json, package.json, src/buttons/FigureCard/FigureCard.test.js, src/buttons/FigureCard/index.jsx
(My mistake ✋). FigureCard does not need to have a "button" element and trigger onClick. This should be handled outside by parent component.
=> Hotfix -> Removed <button> wrapping content in FigureCard component

.gitignore, CHANGELOG.md, package-lock.json, package.json, src/structure/Screen/styles.css, src/structure/Scroll/index.jsx, src/structure/Scroll/styles.css
Some issues because of the same scrolling problem:
## Solution
Layout were not well implemented to achieve its purpose. It was using weird `absolute` position that was not necessary and layout could be built in a different way. This image looks what it was and what it is now:
=> BUG - Fix all scrolling issues

CHANGELOG.md, package-lock.json, package.json, src/structure/Scroll/styles.css
Missed `flex-grow` property to ensure height required is applied for scroll component.
=> Add missing flex property for scroll height

package-lock.json, package.json, src/components/BankAccountNumberInputField/BankAccountNumberInputField.js, src/components/BankAccountNumberInputField/BankAccountNumberInputField.vue, src/components/DateField/DateField.js, src/components/DateField/DateField.vue, src/components/FormField/FormField.js, src/components/PhoneNumberField/PhoneNumberField.js, src/components/PhoneNumberField/PhoneNumberField.stories.js, src/components/PhoneNumberField/PhoneNumberField.vue, src/components/TextField/TextField.js, src/components/TextField/TextField.vue
* Update `FormField` and its derived components to support focus()
* Ensured that all `FormField`-derived components also support the `startFocused` prop.
* Added `isPhoneNumberValid` helper method to the `PhoneNumberField` component and updated its Storybook story to showcase that.
* Local Storybook Testing: **PASS**
=> Update FormField and its derived components to support focus()

package.json, src/components/BankAccountNumberInputField/BankAccountNumberInputField.js, src/components/BankAccountNumberInputField/BankAccountNumberInputField.vue, src/components/FormField/FormField.js, src/components/FormField/FormField.vue
* Updated the `FormField` component to emit a `paste` event.
* Updated the `BankAccountNumberInputField` component to silently remove spaces from pasted values (for mx-merino #662).
**NOTE**: I will be making another PR soon for applying these changes to the old React version of this UI Library (required for applying this improvement to `mx-merino`)
* Tested locally with Storybook
* **Broken** (when trying to paste a value of: `1 2 34 56 789123666678`):
* **Fixed** (when trying to paste a value of: `1 2 34 56 789123666678`):
=> Improve BankAccountNumberInputField (MX-Merino #662)

package-lock.json, package.json, src/components/ComingSoon/ComingSoon.scss, src/components/ComingSoon/ComingSoon.vue, src/components/LoadingSpinner/LoadingSpinner.scss, src/components/SelectBox/SelectBox.scss
* Updated `b2c-mapp-ui-assets` npm dependency to the latest version and fixed a few SVG icon overrides that were broken from the latest assets update.
*  Testing locally with Storybook: **PASS**
=> SVG Icon size fixes after updating to the latest b2c-mapp-ui-assets version

package.json, src/components/Button/Button.js, src/components/Button/Button.stories.js, src/components/Button/Button.vue
This PR will resolve #36 by updating b2c-mapp-ui to ensure that all copy text comes from props (no raw text except for default prop values)
=> Updating b2c-mapp-ui, all copy text comes from props

package.json, src/components/Button/Button.js, src/components/ConfirmationToastDialog/ConfirmationToastDialog.js, src/components/ConfirmationToastDialog/ConfirmationToastDialog.stories.js, src/components/ConfirmationToastDialog/ConfirmationToastDialog.vue, src/components/WrappedButton/WrappedButton.js, src/components/WrappedButton/WrappedButton.stories.js, src/components/WrappedButton/WrappedButton.vue
* Updated the `Button` component to stop emitting a `click` event when in `loading` state.
* Updated `ConfirmationToastDialog` to support the new `loadingText` prop for the `Button` component that it uses.
* Updated `WrappedButton` to support the new `loadingText` prop for the `Button` component that it uses.
* Manual testing with local Storybook: **PASS**
=> Add loadingText props to components that use Button with loading

package-lock.json, package.json, src/components/BankAccountNumberInputField/BankAccountNumberInputField.js, src/components/BankAccountNumberInputField/BankAccountNumberInputField.stories.js, src/components/BankAccountNumberInputField/BankAccountNumberInputField.test.js
* Updated the `BankAccountNumberInputField` adding a new `autoformat` prop (`false` by default) to control whether we add spaces automatically. Also updated the Storybook stories for this component and its Unit Tests.
* Bumped the MINOR version in `package.json`
=> Stop adding spaces in BankAccountNumberInputField by default

package.json, src/components/PhoneNumberField/PhoneNumberField.js, src/components/PhoneNumberField/PhoneNumberField.stories.js, src/components/PhoneNumberField/PhoneNumberField.test.js
* Updated the `hideCountryCode` prop in the `PhonNumberField` component to: `hideCountryCodeUntilFocus` and modified the logic to only hide the country code when there is no value and unfocused. 
* Updated the `PhoneNumberField` unit tests.
* Bumped the MINOR version in `package.json`
=> 219 - Update phone number field per Design Feedback

package-lock.json, package.json, src/components/BankAccountNumberInputField/BankAccountNumberInputField.js, src/components/ConfirmationModalDialog/ConfirmationModalDialog.stories.js, src/components/RadioList/RadioList.stories.js, src/components/RadioList/RadioList.vue, src/components/TextField/TextField.test.js, vue.config.js
* Updated `RadioList` component to accept a new `htmlLabel` property for its options (which will get rendered via the `v-html` directive).  This is needed as part of the `mx-merino` Vue migration
* Updated to the latest npm dependencies.
* Updated this project to use `dart-sass` instead of `node-sass` since that is now the official recommendation from the Webpack team.
* Bumped the PATCH version in `package.json`
=> Add htmlLabel support to RadioList options

package-lock.json, package.json, src/components/DateField/DateField.js, src/components/DateField/DateField.stories.js, src/components/DateField/DateField.vue, src/components/SelectBox/SelectBox.js, src/components/SelectBox/SelectBox.scss, src/components/SelectBox/SelectBox.stories.js, src/components/SelectBox/SelectBox.vue
* Updated `SelectBox` and `DateField` to support `keyup`, `keypress`, `paste`, `blur`, and `focus` events 
* Updated `SelectBox` to support the `errorLabel` prop.
* Added a new `customValidation` prop to `DateField` to allow showing a custom errorLabel.
* Updated Storybook stories for `SelectBox` and `DateField` to showcase their new features.
* Bumped the MINOR version in `package.json`
=> Add keypress and keyup events to select box and date picker

package-lock.json, package.json, src/components/ConfirmationModalDialog/ConfirmationModalDialog.js, src/components/ConfirmationModalDialog/ConfirmationModalDialog.scss, src/components/ConfirmationModalDialog/ConfirmationModalDialog.stories.js, src/components/ConfirmationModalDialog/ConfirmationModalDialog.test.js, src/components/ConfirmationModalDialog/ConfirmationModalDialog.vue
The current `disabled` property affects to both buttons in the `ConfirmationModalDialog`. Once this ConfirmationModalDialog is visible, it can not be possible to close it because both buttons are disabled.
The goal of this task is to provide a way to disable each button separately. `confirmButtonDisabled` & `dismissButtonDisabled`
- Tested in Storybook
- Unit tested
`black-400` color applied to disabled button:
=> Disable confirm dialog button

package.json, src/components/SelectBox/SelectBox.js, src/components/SelectBox/SelectBox.stories.js, src/components/SelectBox/SelectBox.vue
* Fixed how SelectBox displays an empty selection when there is a default option with no value.
* Added a new Storybook story for this issue
* **Before** (Broken):
* **After** (Fixed):
=> Improve how SelectBox handles default option with empty value

package.json, src/components/PhoneNumberField/PhoneNumberField.js, src/components/PhoneNumberField/PhoneNumberField.stories.js
This PR will update the PhoneNumberField component in order to add a maxPhoneNumberLength
(The default max-length will be 10 digits)
Also, this PR forms part in solving issue https://github.com/lana/b2c-access/issues/281
This was tested locally using storybook
=> Adding maxPhoneNumberLength to PhoneNumberField component

package-lock.json, package.json, src/components/ContentItem/ContentItem.js, src/components/ContentItem/ContentItem.scss, src/components/ContentItem/ContentItem.stories.js, src/components/ContentItem/ContentItem.vue
* Added `noBorder` prop to `ContentItem`
=> Added noBorder prop to ContentItem

package-lock.json, package.json, src/components/DateField/DateField.scss, src/components/SelectBox/SelectBox.scss, src/components/SelectBox/SelectBox.vue
* Updated the icon size for `SelectBox` and `DateField` components to match Figma designs.
* Update `SelectBox` to stop showing the dropdown icon when `disabled`
* `npm run lint`: **PASS** 
* `npm run test`: **PASS** 
* `npm run prepare`: **PASS** 
=> Update SelectBox and DateField icons

package-lock.json, package.json, src/components/CurrencyField/CurrencyField.js, src/components/CurrencyField/CurrencyField.stories.js, src/lib/sleepHelper.js
* Updated the `CurrencyField` component's `value` prop to accept either a `Number` or a `String`.
* Fixed logic for initial `null`/`undefined` values for `CurrencyField` and added a story for that scenario.
* Updated NPM dependencies
=> CurrencyField updates and improvements

package-lock.json, package.json, src/components/BankAccountNumberInputField/BankAccountNumberInputField.js, src/components/BankAccountNumberInputField/BankAccountNumberInputField.stories.js, src/components/BankAccountNumberInputField/BankAccountNumberInputField.test.js, src/components/BankAccountNumberInputField/BankAccountNumberInputField.vue
* Updated `BankAccountNumberField` adding a new `lengthHint` prop for overriding the length hint that is shown (which previously was set to always use the maxlength value).
* Updated NPM dependencies.
=> Added lengthHint prop to BankAccountNumberField

package-lock.json, package.json, src/components/SlideButton/SlideButton.js, src/components/SlideButton/SlideButton.scss, src/components/SlideButton/SlideButton.stories.js, src/components/SlideButton/SlideButton.vue
* Updated the `SlideButton` component to match the latest designs in Figma
* Bumped the `PATCH` version in `package.json`.
* **Before (old)**:
* **After (new)**:
=> Updated SlideButton Design

package-lock.json, package.json, src/library.js
Add CallToActionScreen to library.js, bumped version to 8.1.0
- npm run lint: **PASS**
- npm run test: **PASS**
=> Add CallToActionScreen to library.js

package-lock.json, package.json, src/components/FormField/FormField.scss
* Removed a `line-height` override from `FormField.scss` (only realized it was a problem after testing with the real fonts with `b2c-access`.
* Updated NPM dependencies
=> Small design fixes

package-lock.json, package.json, src/components/CurrencyField/CurrencyField.scss, src/components/FormField/FormField.scss, src/components/PhoneNumberField/PhoneNumberField.scss
* Removed the blue tap highlight color from the clear icon for `FormField` and `CurrencyField`
* Fixed the CSS `line-height` attribute for the flag icon in `PhoneNumberField` (this was causing issues for some devices)
* Local testing with Storybook (and Chrome's mobile device simulator): **PASS**
=> More style fixes for FormField's Clear Button and PhoneNumberField's flag icon

package-lock.json, package.json, src/components/PhoneNumberField/PhoneNumberField.vue, src/components/SelectBox/SelectBox.vue
* Added a `data-testid` attribute to the `SelectBox`'s container element.
* Changed the `PhoneNumberField`'s flag emoji container from `<p>` to: `<div>` (in hopes of potentially improving how it renders for some Android devices).
* Updated npm dependencies
=> Add test-id for SelectBox

package-lock.json, package.json, src/components/PhoneNumberField/PhoneNumberField.js, src/components/PhoneNumberField/PhoneNumberField.scss, src/components/PhoneNumberField/PhoneNumberField.vue
* Removed the Flag emoji from `PhoneNumberField` (per the Design team's request)
* Bumped the `MINOR` version in `package.json`
=> Remove Flag emoji from PhoneNumberField

package-lock.json, package.json
Include new version of the assets library to start using new cashPayment icon version:
- Tested in Storybook.
=> update assets lib version

package-lock.json, package.json, src/components/ToggleSwitch/ToggleSwitch.js, src/components/ToggleSwitch/ToggleSwitch.scss, src/components/ToggleSwitch/ToggleSwitch.stories.js, src/components/ToggleSwitch/ToggleSwitch.vue
* Updated `ToggleSwitch` adding new `buttons` prop (and related button label props) for showing toggle buttons instead of a switch.
* Updated Storybook stories to show the new buttons mode.
* Updated npm dependencies.
* Bumped the `MINOR` version in `package.json`
=> Toggle buttons

package-lock.json, package.json, src/components/ContentItem/ContentItem.js, src/components/ContentItem/ContentItem.stories.js, src/components/ContentItem/ContentItem.test.js, src/components/ContentItem/ContentItem.vue
Allow title and metatext to have html as content
=> ContentItem html on title and MetaText

package-lock.json, package.json, src/components/ContentItem/ContentItem.stories.js, src/components/ContentRadioList/ContentRadioList.js, src/components/ContentRadioList/ContentRadioList.scss, src/components/ContentRadioList/ContentRadioList.stories.js, src/components/ContentRadioList/ContentRadioList.test.js, src/components/ContentRadioList/ContentRadioList.vue
Add a new radio list with a custom content and radio to the right
Custom icons / default behavior
=> ContentRadioList

package-lock.json, package.json, src/components/CopyableListItem/CopyableListItem.js, src/components/CopyableListItem/CopyableListItem.stories.js, src/components/CopyableListItem/CopyableListItem.test.js, src/components/CopyableListItem/CopyableListItem.vue
Propagate CopyToClipboardButton click event
=> Propagate click event on copy

package-lock.json, package.json, src/components/AmountInput/AmountInput.js, src/components/AmountInput/AmountInput.scss, src/components/AmountInput/AmountInput.stories.js, src/components/AmountInput/AmountInput.test.js, src/components/AmountInput/AmountInput.vue
There are some times where values where incorrectly converted to Number giving them `null` as response. This task enforce a better conversion based on currency parts, like symbol and group value.
=> Fix AmountInput number conversion

package-lock.json, package.json, src/components/AmountInput/AmountInput.js, src/lib/regexHelper.js
`replaceAll` was not broadly accepted, specially for Huawei devices. Moved function from `replaceAll` to `replace` with global flag
=> AmountInput replace function

package-lock.json, package.json, src/components/Progress/Progress.scss
Design of the progress border with the color does not exists, so it is removed
=> Fix Progress borders

package-lock.json, package.json, src/components/Button/Button.js, src/components/Button/Button.stories.js, src/components/Button/Button.test.js, src/components/Button/Button.vue, src/components/CallToActionScreen/CallToActionScreen.js, src/components/CallToActionScreen/CallToActionScreen.vue, src/components/ForwardButton/ForwardButton.js, src/components/ForwardButton/ForwardButton.vue, src/components/WrappedButton/WrappedButton.js, src/components/WrappedButton/WrappedButton.vue
Added the possibility to accept debounce as parameter to make a delay on multiclicks for Button, WrappedButton, CallToAction, ForwardButton
Add `debounce` parameter to one of the component mentioned before and  try to click multiple times, only on `click` event will be emitter
=> Button's click debounce

package-lock.json, package.json, src/components/Carousel/Carousel.js
Change from HTMLCollection getter to an Array definition, so `findIndex` won't fail
=> Fix Carousel items setter

package-lock.json, package.json, src/components/Carousel/Carousel.js, src/components/Carousel/Carousel.vue
Sometimes the navigation is overridden by the watcher of `currentIndex` and doesn't allow the user to scroll to the desire slide. With the help of a `destinationScrollLeft` every intermediary index is not considered
=> Fix Carousel navigation

package-lock.json, package.json, src/components/Carousel/Carousel.js, src/components/Carousel/Carousel.test.js
Fix Carousel slide selection being wrong after resizing
=> Carousel resize observer

package-lock.json, package.json, src/components/AmountInput/AmountInput.js, src/components/AmountInput/AmountInput.stories.js, src/components/AmountInput/AmountInput.test.js
AmountInput was not correctly handling thousand separator for CLP, as `10.000` became `10` and `1.000.000` became `null`. `parse` must include options to handle that.
=> Fix AmountInput locale parse

package-lock.json, package.json, src/components/PhoneNumberField/PhoneNumberField.js, src/components/PhoneNumberField/PhoneNumberField.test.js
Fix validation for PhoneNumberField, as with some numbers that add parenthesis `()` it is considered bad numbers
=> Fix PhoneNumberField validator

package-lock.json, package.json, src/components/CarouselItem/CarouselItem.scss
Avoid a pass-over scroll within the Carousel by using the `snap-scroll-stop` attribute, available on Chrome
=> CarouselItem scroll limits

package-lock.json, package.json, src/components/LinearProgress/LinearProgress.js, src/components/LinearProgress/LinearProgress.test.js, src/components/Progress/Progress.js, src/components/Progress/Progress.test.js
Animation API isn't available on tests, so when animated the tests are failing
=> Fix animation error for tests

package-lock.json, package.json, src/components/LinearProgress/LinearProgress.scss, src/components/LinearProgress/LinearProgress.stories.js, src/components/LinearProgress/LinearProgress.vue
Remove border from container so progress color is above background and border color
=> Fix LinearProgress background progress

package-lock.json, package.json, src/components/ConfirmationModalDialog/ConfirmationModalDialog.stories.js, src/components/ConfirmationModalDialog/ConfirmationModalDialog.test.js, src/components/ConfirmationModalDialog/ConfirmationModalDialog.vue
Added a new slot for ConfirmationModalDialog for custom purposes, like adding a custom close button
=> ConfirmationModalDialog extra slot

package-lock.json, package.json, src/components/AmountInput/AmountInput.js, src/components/AmountInput/AmountInput.vue, src/main.js
Rollback to previous import method of ContentEditable regarding sfc standard recommendation
=> Fix ContentEditable sfc import

package-lock.json, package.json, src/components/CodeInputField/CodeInputField.js, src/components/CodeInputField/CodeInputField.vue
Fix current behavior and make `autocomplete` optional, default to `'off'`
=> CodeInputField autocomplete behavior

package-lock.json, package.json, src/components/ActionItem/ActionItem.stories.js, src/components/Carousel/Carousel.js, src/components/ToggleSwitch/ToggleSwitch.scss
According to [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft), some systems using display scaling may give decimal values, so a change on the position detection have to be changed to a more `|scrollLeft - itemLeft| < 1`
=> Fix Carousel behavior for system using display scaling

package-lock.json, package.json, src/components/CallToActionScreen/CallToActionScreen.js, src/components/CallToActionScreen/CallToActionScreen.test.js
Fix event handler of CallToActionScreen by adding `emits` property as the were not correctly handled
=> Fix CallToActionScreen emits property

package-lock.json, package.json, src/components/ActionItem/ActionItem.js, src/components/ActionItem/ActionItem.stories.js, src/components/ActionItem/ActionItem.vue, src/components/BoxContentItem/BoxContentItem.js, src/components/BoxContentItem/BoxContentItem.vue, src/components/Carousel/Carousel.vue, src/components/ContentItem/ContentItem.js, src/components/ContentItem/ContentItem.vue, src/components/ListItem/ListItem.js, src/components/ListItem/ListItem.vue
In Vue 3, slots are now methods, so a change of the way to detect it's presence should be done. `v-if` comments are now treated as `Comment` node, so a `slot` with a `v-if` contains element inside, so we should check that every content is not a comment to know if its empty
=> Fix slot content detection

.eslintrc.js, .github/workflows/mergepr.yml, .github/workflows/nodejs.yml, src/components/PhoneNumberField/PhoneNumberField.ts, src/components/Steps/Step.vue, src/components/Steps/Steps.scss, src/components/Steps/Steps.stories.ts, src/components/Steps/Steps.test.ts, src/components/Steps/Steps.ts, src/components/Steps/Steps.vue, src/components/StorybookMobileDeviceSimulator/StorybookMobileDeviceSimulator.stories.ts, src/components/StorybookMobileDeviceSimulator/StorybookMobileDeviceSimulator.ts, src/components/StorybookMobileDeviceSimulator/StorybookMobileDeviceSimulator.utils.ts, src/components/TextParagraph/TextParagraph.stories.ts, src/components/TextParagraph/TextParagraph.ts, src/lib/storybookHelpers.ts, src/library.ts, tsconfig.json
Add a simple Steps component that list elements after a dot
Add a Step element that allows the user to customize dot
Just Steps: 
With custom dot and step elements
=> Steps and Step component

package-lock.json, package.json, src/components/Button/Button.stories.ts, src/components/Button/Button.ts
When href is not set it takes the default value `''` which is not the desired value as it expect to be redirected to the same page.
Create a <Button link></Button>, click on them, expect to do nothing
=> Fix empty href on button link behavior
